# Generated by Django 3.0.8 on 2020-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200730_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
