# Generated by Django 3.0.8 on 2020-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('placeholder', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='photos/profile')),
                ('what_i_do', models.CharField(max_length=500)),
                ('more_about_me', models.CharField(max_length=500)),
                ('social', models.ImageField(upload_to='photos/social')),
                ('top_skills', models.ManyToManyField(to='details.Skill')),
            ],
        ),
    ]
