# Generated by Django 3.0.8 on 2020-07-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='more_about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='placeholder',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='detail',
            name='what_i_do',
            field=models.TextField(),
        ),
    ]
